//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogFileCheck.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUM2:AUM")]
        public string txt_rangeWeldingDistance {
            get {
                return ((string)(this["txt_rangeWeldingDistance"]));
            }
            set {
                this["txt_rangeWeldingDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\02.DataLogFile_31.10.2022Copy.xlsx")]
        public string txt_logfile {
            get {
                return ((string)(this["txt_logfile"]));
            }
            set {
                this["txt_logfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.16")]
        public double txt_rangeWeldingDistanceValLSL {
            get {
                return ((double)(this["txt_rangeWeldingDistanceValLSL"]));
            }
            set {
                this["txt_rangeWeldingDistanceValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public string txt_rangeWeldingDistanceValUSL {
            get {
                return ((string)(this["txt_rangeWeldingDistanceValUSL"]));
            }
            set {
                this["txt_rangeWeldingDistanceValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUK2:AUK")]
        public string txt_rangeWeldingDistanceLSL {
            get {
                return ((string)(this["txt_rangeWeldingDistanceLSL"]));
            }
            set {
                this["txt_rangeWeldingDistanceLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUP2:AUP")]
        public string txt_rangeWeldingDistanceUSL {
            get {
                return ((string)(this["txt_rangeWeldingDistanceUSL"]));
            }
            set {
                this["txt_rangeWeldingDistanceUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUS2:AUS")]
        public string txt_rangeWeldingEnergy {
            get {
                return ((string)(this["txt_rangeWeldingEnergy"]));
            }
            set {
                this["txt_rangeWeldingEnergy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double txt_rangeWeldingEnergyValLSL {
            get {
                return ((double)(this["txt_rangeWeldingEnergyValLSL"]));
            }
            set {
                this["txt_rangeWeldingEnergyValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string txt_rangeWeldingEnergyValUSL {
            get {
                return ((string)(this["txt_rangeWeldingEnergyValUSL"]));
            }
            set {
                this["txt_rangeWeldingEnergyValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUQ2:AUQ")]
        public string txt_rangeWeldingEnergyLSL {
            get {
                return ((string)(this["txt_rangeWeldingEnergyLSL"]));
            }
            set {
                this["txt_rangeWeldingEnergyLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUV2:AUV")]
        public string txt_rangeWeldingEnergyUSL {
            get {
                return ((string)(this["txt_rangeWeldingEnergyUSL"]));
            }
            set {
                this["txt_rangeWeldingEnergyUSL"] = value;
            }
        }
    }
}
