//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogFileCheck.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUM2:AUM")]
        public string txt_rangeWeldingDistance {
            get {
                return ((string)(this["txt_rangeWeldingDistance"]));
            }
            set {
                this["txt_rangeWeldingDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Roboti\\MFU\\02.DataLogFile_31.10.2022Copy.xlsx")]
        public string txt_logfile {
            get {
                return ((string)(this["txt_logfile"]));
            }
            set {
                this["txt_logfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.16")]
        public double txt_rangeWeldingDistanceValLSL {
            get {
                return ((double)(this["txt_rangeWeldingDistanceValLSL"]));
            }
            set {
                this["txt_rangeWeldingDistanceValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public string txt_rangeWeldingDistanceValUSL {
            get {
                return ((string)(this["txt_rangeWeldingDistanceValUSL"]));
            }
            set {
                this["txt_rangeWeldingDistanceValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUK2:AUK")]
        public string txt_rangeWeldingDistanceLSL {
            get {
                return ((string)(this["txt_rangeWeldingDistanceLSL"]));
            }
            set {
                this["txt_rangeWeldingDistanceLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUP2:AUP")]
        public string txt_rangeWeldingDistanceUSL {
            get {
                return ((string)(this["txt_rangeWeldingDistanceUSL"]));
            }
            set {
                this["txt_rangeWeldingDistanceUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUS2:AUS")]
        public string txt_rangeWeldingEnergy {
            get {
                return ((string)(this["txt_rangeWeldingEnergy"]));
            }
            set {
                this["txt_rangeWeldingEnergy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double txt_rangeWeldingEnergyValLSL {
            get {
                return ((double)(this["txt_rangeWeldingEnergyValLSL"]));
            }
            set {
                this["txt_rangeWeldingEnergyValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string txt_rangeWeldingEnergyValUSL {
            get {
                return ((string)(this["txt_rangeWeldingEnergyValUSL"]));
            }
            set {
                this["txt_rangeWeldingEnergyValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUQ2:AUQ")]
        public string txt_rangeWeldingEnergyLSL {
            get {
                return ((string)(this["txt_rangeWeldingEnergyLSL"]));
            }
            set {
                this["txt_rangeWeldingEnergyLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUV2:AUV")]
        public string txt_rangeWeldingEnergyUSL {
            get {
                return ((string)(this["txt_rangeWeldingEnergyUSL"]));
            }
            set {
                this["txt_rangeWeldingEnergyUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AVX2:AVX")]
        public string txt_rangeAirFlowFlowVolume {
            get {
                return ((string)(this["txt_rangeAirFlowFlowVolume"]));
            }
            set {
                this["txt_rangeAirFlowFlowVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double txt_rangeAirFlowFlowVolumeValLSL {
            get {
                return ((double)(this["txt_rangeAirFlowFlowVolumeValLSL"]));
            }
            set {
                this["txt_rangeAirFlowFlowVolumeValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double txt_rangeAirFlowFlowVolumeValUSL {
            get {
                return ((double)(this["txt_rangeAirFlowFlowVolumeValUSL"]));
            }
            set {
                this["txt_rangeAirFlowFlowVolumeValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AVV2:AVV")]
        public string txt_rangeAirFlowFlowVolumeLSL {
            get {
                return ((string)(this["txt_rangeAirFlowFlowVolumeLSL"]));
            }
            set {
                this["txt_rangeAirFlowFlowVolumeLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AWA2:AWA")]
        public string txt_rangeAirFlowFlowVolumeUSL {
            get {
                return ((string)(this["txt_rangeAirFlowFlowVolumeUSL"]));
            }
            set {
                this["txt_rangeAirFlowFlowVolumeUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRB2:BRB")]
        public string txt_rangeScara1FittingPins0 {
            get {
                return ((string)(this["txt_rangeScara1FittingPins0"]));
            }
            set {
                this["txt_rangeScara1FittingPins0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara1FittingPins0ValUSL {
            get {
                return ((double)(this["txt_rangeScara1FittingPins0ValUSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins0ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRE2:BRE")]
        public string txt_rangeScara1FittingPins0USL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins0USL"]));
            }
            set {
                this["txt_rangeScara1FittingPins0USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara1FittingPins0ValLSL {
            get {
                return ((double)(this["txt_rangeScara1FittingPins0ValLSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins0ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRA2:BRA")]
        public string txt_rangeScara1FittingPins0LSL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins0LSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins0LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRJ2:BRJ")]
        public string txt_rangeScara1FittingPins1 {
            get {
                return ((string)(this["txt_rangeScara1FittingPins1"]));
            }
            set {
                this["txt_rangeScara1FittingPins1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string txt_rangeScara1FittingPins1ValLSL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins1ValLSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins1ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public string txt_rangeScara1FittingPins1ValUSL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins1ValUSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins1ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRI2:BRI")]
        public string txt_rangeScara1FittingPins1LSL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins1LSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins1LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRM2:BRM")]
        public string txt_rangeScara1FittingPins1USL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins1USL"]));
            }
            set {
                this["txt_rangeScara1FittingPins1USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRR2:BRR")]
        public string txt_rangeScara1FittingPins2 {
            get {
                return ((string)(this["txt_rangeScara1FittingPins2"]));
            }
            set {
                this["txt_rangeScara1FittingPins2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara1FittingPins2ValUSL {
            get {
                return ((double)(this["txt_rangeScara1FittingPins2ValUSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins2ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara1FittingPins2ValLSL {
            get {
                return ((double)(this["txt_rangeScara1FittingPins2ValLSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins2ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRQ2:BRQ")]
        public string txt_rangeScara1FittingPins2LSL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins2LSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins2LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRU2:BRU")]
        public string txt_rangeScara1FittingPins2USL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins2USL"]));
            }
            set {
                this["txt_rangeScara1FittingPins2USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRZ2:BRZ")]
        public string txt_rangeScara1FittingPins3 {
            get {
                return ((string)(this["txt_rangeScara1FittingPins3"]));
            }
            set {
                this["txt_rangeScara1FittingPins3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara1FittingPins3ValUSL {
            get {
                return ((double)(this["txt_rangeScara1FittingPins3ValUSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins3ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara1FittingPins3ValLSL {
            get {
                return ((double)(this["txt_rangeScara1FittingPins3ValLSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins3ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRY2:BRY")]
        public string txt_rangeScara1FittingPins3LSL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins3LSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins3LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BSC2:BSC")]
        public string txt_rangeScara1FittingPins3USL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins3USL"]));
            }
            set {
                this["txt_rangeScara1FittingPins3USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BSH2:BSH")]
        public string txt_rangeScara1FittingPins4 {
            get {
                return ((string)(this["txt_rangeScara1FittingPins4"]));
            }
            set {
                this["txt_rangeScara1FittingPins4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara1FittingPins4ValUSL {
            get {
                return ((double)(this["txt_rangeScara1FittingPins4ValUSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins4ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara1FittingPins4ValLSL {
            get {
                return ((double)(this["txt_rangeScara1FittingPins4ValLSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins4ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BSG2:BSG")]
        public string txt_rangeScara1FittingPins4LSL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins4LSL"]));
            }
            set {
                this["txt_rangeScara1FittingPins4LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BSK2:BSK")]
        public string txt_rangeScara1FittingPins4USL {
            get {
                return ((string)(this["txt_rangeScara1FittingPins4USL"]));
            }
            set {
                this["txt_rangeScara1FittingPins4USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BTH2:BTH")]
        public string txt_rangeScara2FittingPins0 {
            get {
                return ((string)(this["txt_rangeScara2FittingPins0"]));
            }
            set {
                this["txt_rangeScara2FittingPins0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara2FittingPins0ValUSL {
            get {
                return ((double)(this["txt_rangeScara2FittingPins0ValUSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins0ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara2FittingPins0ValLSL {
            get {
                return ((double)(this["txt_rangeScara2FittingPins0ValLSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins0ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BTG2:BTG")]
        public string txt_rangeScara2FittingPins0LSL {
            get {
                return ((string)(this["txt_rangeScara2FittingPins0LSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins0LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BTK2:BTK")]
        public string txt_rangeScara2FittingPins0USL {
            get {
                return ((string)(this["txt_rangeScara2FittingPins0USL"]));
            }
            set {
                this["txt_rangeScara2FittingPins0USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BTP2:BTP")]
        public string txt_rangeScara2FittingPins1 {
            get {
                return ((string)(this["txt_rangeScara2FittingPins1"]));
            }
            set {
                this["txt_rangeScara2FittingPins1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara2FittingPins1ValUSL {
            get {
                return ((double)(this["txt_rangeScara2FittingPins1ValUSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins1ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara2FittingPins1ValLSL {
            get {
                return ((double)(this["txt_rangeScara2FittingPins1ValLSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins1ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BTO2:BTO")]
        public string txt_rangeScara2FittingPins1LSL {
            get {
                return ((string)(this["txt_rangeScara2FittingPins1LSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins1LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BTS2:BTS")]
        public string txt_rangeScara2FittingPins1USL {
            get {
                return ((string)(this["txt_rangeScara2FittingPins1USL"]));
            }
            set {
                this["txt_rangeScara2FittingPins1USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BTX2:BTX")]
        public string txt_rangeScara2FittingPins2 {
            get {
                return ((string)(this["txt_rangeScara2FittingPins2"]));
            }
            set {
                this["txt_rangeScara2FittingPins2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara2FittingPins2ValUSL {
            get {
                return ((double)(this["txt_rangeScara2FittingPins2ValUSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins2ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara2FittingPins2ValLSL {
            get {
                return ((double)(this["txt_rangeScara2FittingPins2ValLSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins2ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BTW2:BTW")]
        public string txt_rangeScara2FittingPins2LSL {
            get {
                return ((string)(this["txt_rangeScara2FittingPins2LSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins2LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUA2:BUA")]
        public string txt_rangeScara2FittingPins2USL {
            get {
                return ((string)(this["txt_rangeScara2FittingPins2USL"]));
            }
            set {
                this["txt_rangeScara2FittingPins2USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUF2:BUF")]
        public string txt_rangeScara2FittingPins3 {
            get {
                return ((string)(this["txt_rangeScara2FittingPins3"]));
            }
            set {
                this["txt_rangeScara2FittingPins3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara2FittingPins3ValUSL {
            get {
                return ((double)(this["txt_rangeScara2FittingPins3ValUSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins3ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara2FittingPins3ValLSL {
            get {
                return ((double)(this["txt_rangeScara2FittingPins3ValLSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins3ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUE2:BUE")]
        public string txt_rangeScara2FittingPins3LSL {
            get {
                return ((string)(this["txt_rangeScara2FittingPins3LSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins3LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUI2:BUI")]
        public string txt_rangeScara2FittingPins3USL {
            get {
                return ((string)(this["txt_rangeScara2FittingPins3USL"]));
            }
            set {
                this["txt_rangeScara2FittingPins3USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUN2:BUN")]
        public string txt_rangeScara2FittingPins4 {
            get {
                return ((string)(this["txt_rangeScara2FittingPins4"]));
            }
            set {
                this["txt_rangeScara2FittingPins4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara2FittingPins4ValUSL {
            get {
                return ((double)(this["txt_rangeScara2FittingPins4ValUSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins4ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara2FittingPins4ValLSL {
            get {
                return ((double)(this["txt_rangeScara2FittingPins4ValLSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins4ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUM2:BUM")]
        public string txt_rangeScara2FittingPins4LSL {
            get {
                return ((string)(this["txt_rangeScara2FittingPins4LSL"]));
            }
            set {
                this["txt_rangeScara2FittingPins4LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUQ2:BUQ")]
        public string txt_rangeScara2FittingPins4USL {
            get {
                return ((string)(this["txt_rangeScara2FittingPins4USL"]));
            }
            set {
                this["txt_rangeScara2FittingPins4USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BVN2:BVN")]
        public string txt_rangeScara3FittingPins0 {
            get {
                return ((string)(this["txt_rangeScara3FittingPins0"]));
            }
            set {
                this["txt_rangeScara3FittingPins0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara3FittingPins0ValUSL {
            get {
                return ((double)(this["txt_rangeScara3FittingPins0ValUSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins0ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara3FittingPins0ValLSL {
            get {
                return ((double)(this["txt_rangeScara3FittingPins0ValLSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins0ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BVM2:BVM")]
        public string txt_rangeScara3FittingPins0LSL {
            get {
                return ((string)(this["txt_rangeScara3FittingPins0LSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins0LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BVQ2:BVQ")]
        public string txt_rangeScara3FittingPins0USL {
            get {
                return ((string)(this["txt_rangeScara3FittingPins0USL"]));
            }
            set {
                this["txt_rangeScara3FittingPins0USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BVV2:BVV")]
        public string txt_rangeScara3FittingPins1 {
            get {
                return ((string)(this["txt_rangeScara3FittingPins1"]));
            }
            set {
                this["txt_rangeScara3FittingPins1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara3FittingPins1ValUSL {
            get {
                return ((double)(this["txt_rangeScara3FittingPins1ValUSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins1ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara3FittingPins1ValLSL {
            get {
                return ((double)(this["txt_rangeScara3FittingPins1ValLSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins1ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BVU2:BVU")]
        public string txt_rangeScara3FittingPins1LSL {
            get {
                return ((string)(this["txt_rangeScara3FittingPins1LSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins1LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BVY2:BVY")]
        public string txt_rangeScara3FittingPins1USL {
            get {
                return ((string)(this["txt_rangeScara3FittingPins1USL"]));
            }
            set {
                this["txt_rangeScara3FittingPins1USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BWD2:BWD")]
        public string txt_rangeScara3FittingPins2 {
            get {
                return ((string)(this["txt_rangeScara3FittingPins2"]));
            }
            set {
                this["txt_rangeScara3FittingPins2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara3FittingPins2ValUSL {
            get {
                return ((double)(this["txt_rangeScara3FittingPins2ValUSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins2ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara3FittingPins2ValLSL {
            get {
                return ((double)(this["txt_rangeScara3FittingPins2ValLSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins2ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BWC2:BWC")]
        public string txt_rangeScara3FittingPins2LSL {
            get {
                return ((string)(this["txt_rangeScara3FittingPins2LSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins2LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BWG2:BWG")]
        public string txt_rangeScara3FittingPins2USL {
            get {
                return ((string)(this["txt_rangeScara3FittingPins2USL"]));
            }
            set {
                this["txt_rangeScara3FittingPins2USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BWL2:BWL")]
        public string txt_rangeScara3FittingPins3 {
            get {
                return ((string)(this["txt_rangeScara3FittingPins3"]));
            }
            set {
                this["txt_rangeScara3FittingPins3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara3FittingPins3ValUSL {
            get {
                return ((double)(this["txt_rangeScara3FittingPins3ValUSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins3ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara3FittingPins3ValLSL {
            get {
                return ((double)(this["txt_rangeScara3FittingPins3ValLSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins3ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BWK2:BWK")]
        public string txt_rangeScara3FittingPins3LSL {
            get {
                return ((string)(this["txt_rangeScara3FittingPins3LSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins3LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BWO2:BWO")]
        public string txt_rangeScara3FittingPins3USL {
            get {
                return ((string)(this["txt_rangeScara3FittingPins3USL"]));
            }
            set {
                this["txt_rangeScara3FittingPins3USL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BWT2:BWT")]
        public string txt_rangeScara3FittingPins4 {
            get {
                return ((string)(this["txt_rangeScara3FittingPins4"]));
            }
            set {
                this["txt_rangeScara3FittingPins4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double txt_rangeScara3FittingPins4ValUSL {
            get {
                return ((double)(this["txt_rangeScara3FittingPins4ValUSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins4ValUSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double txt_rangeScara3FittingPins4ValLSL {
            get {
                return ((double)(this["txt_rangeScara3FittingPins4ValLSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins4ValLSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BWS2:BWS")]
        public string txt_rangeScara3FittingPins4LSL {
            get {
                return ((string)(this["txt_rangeScara3FittingPins4LSL"]));
            }
            set {
                this["txt_rangeScara3FittingPins4LSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BWW2:BWW")]
        public string txt_rangeScara3FittingPins4USL {
            get {
                return ((string)(this["txt_rangeScara3FittingPins4USL"]));
            }
            set {
                this["txt_rangeScara3FittingPins4USL"] = value;
            }
        }
    }
}
